### ISSUE TITLE
Spinner Not Stopping on max value

### ISSUE THREAD

**Issue by stevensoftwaredev** [shaack/bootstrap-input-spinner#1]
My spinner will not stop on max amount. It goes 2 steps above every time if you just hold it down. Once you click back on it goes to max and then starts down if you pressing down. This happens to all the spinners I have on the page also.

**Comment by shaack** [comment]
Which Browser and Operating System?

**Comment by shaack** [comment]
Ok, I see it on the Demo page with Firefox.

**Comment by shaack** [comment]
Thanks for reporting, it should be fixed now.  => V 1.3.22

**Comment by shaack** [comment]
This would be not trivial, because inches is in 12er system, not decimal. It is possible but difficult. One must rethink the whole code-design of the spinner to enable feet and inches, because the value is stored as float and all calculations are done in decimal system for now.

**Comment by stevensoftwaredev** [comment]
I changed the plugin you did on the my version to do feet and inches. I put
the code on jsfiddle in case you wanted it for your plugin. I put notes on
what i changed.

<script async src="//jsfiddle.net/steven27030/bkmyw6uj/embed/"></script>

again thank you.

**Comment by stevensoftwaredev** [comment]
i forked yours and changed it. Im a rookie at this so hopefully i did it
right.

**Comment by shaack** [comment]
Hi, thanks. Looks good. I am also just in it (GitHub) since 1/2 year, so I am also not really a GitHub pro. For information purpose, I think it would be a good idea, to add a comment in the forked sourcecode. Something like:
```
/**
 * Author: Stefan Haack (https://github.com/shaack)
 * License: MIT, see file 'LICENSE'
 * Modified by stevensoftwaredev (or your real name) to display feet and inches. 
 */
```
And maybe also in the README.md, so everyone knows how your forked spinner works. Maybe there are some people out there who also need a feet and inches input.
Thanks, have fun,
Stefan
