### ISSUE TITLE
Button wrapping

### ISSUE THREAD

**Issue by jrichview** [shaack/bootstrap-input-spinner#29]
Spinner is a nice control (thanks!), but I'm having problems with the plus button (button on right hand side of the text input) wrapping to underneath the text input. Obviously that makes it look pretty screwy. 

My text input is inside of a td and I have set a specific width on it in order to keep it from hogging more space than it needs to enter a 2-digit age. Looks great when my browser is maxed, but as I shrink the width, not so great.

**Comment by shaack** [comment]
I am not shure, but isn't this more an issue of the bootstrap `input-group`? If not, could you please provide an example page for the issue?

**Comment by jrichview** [comment]
This is a dummy layout page with no functionality: https://apalacheectrpoc20190312090704.azurewebsites.net/home/problemdemo

If the width of the browser is quite wide it functions correctly.  If you reduce it, the button on the right hand side wraps.

**Comment by jboyer87** [comment]
@jrichview I took a look at your example. Might I suggest adding `white-space: nowrap` to your `<th>`? The problem is not necessarily with the plugin, but with your table layout. You can create a utility class and add it to the table-headers where you have content where text-wrapping would be problematic. See the screenshot for a demo:

![image](https://user-images.githubusercontent.com/5115300/55517597-cfb47680-5625-11e9-9767-9a374b1d20aa.png)

**Comment by shaack** [comment]
You could also add `flex-nowrap` to the input-group class via configuration, see: https://getbootstrap.com/docs/4.3/components/input-group/#wrapping in the bootstrap documentation and https://github.com/shaack/bootstrap-input-spinner#configuration in this README. (`groupClass: "flex-nowrap"`)

**Comment by jrichview** [comment]
That does seem to nail it down. Thanks!
