### ISSUE TITLE
decimal stepping not working (like normal input number one)

### ISSUE THREAD

**Issue by simon387** [shaack/bootstrap-input-spinner#79]
if I have 1.01 and add 1 with stepper, the result is 2.00 and not 2.01

**Comment by shaack** [comment]
False, the behaviour is correct. Compare it with the native, browser rendered type="number" input:
https://shaack.com/projekte/bootstrap-input-spinner/test-native.html
If step is set to "1" and value to "1.01" the native, browser rendered control jumps also from 1.01 to 2.

**Comment by shaack** [comment]
From the specification of the input type="number":
`Only values which are equal to the basis for stepping (min if specified, value otherwise, and an appropriate default value if neither of those is provided) are valid.`
and
`"Note: When the data entered by the user doesn't adhere to the stepping configuration, the user agent may round to the nearest valid value, preferring numbers in the positive direction when there are two equally close options."`

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by shaack** [comment]
That's right, the stepping algerythm needs to be revised at this point. Specification: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

`"Only values which are equal to the basis for stepping (min if specified, value otherwise, and an appropriate default value if neither of those is provided) are valid."`

and

`Note: When the data entered by the user doesn't adhere to the stepping configuration, the user agent may round to the nearest valid value, preferring numbers in the positive direction when there are two equally close options.`

So, if value was set to "1.01" the stepper should step to "2.01".

**Comment by shaack** [comment]
Duplicate, see https://github.com/shaack/bootstrap-input-spinner/issues/56
