### ISSUE TITLE
how to create dynamic multiple input spinner in one page without multiple initialization?

### ISSUE THREAD

**Issue by jyotipathania** [shaack/bootstrap-input-spinner#95]

**Comment by jyotipathania** [comment]
I apologies for the irrelevant post. Thankyou..

**Comment by shaack** [comment]
Oh sorry, I thought it was SPAM because of the mask ad, but I guess that was an example of implementation. It's a jQuery plugin, so you just need to combine all the elements in the query string. Example: $(".makeMeInputSpinner").inputSpinner() for all element with class .makeMeInputSpinner. See also: https://learn.jquery.com/plugins/
